name: book_app_server_side
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  get: ^4.6.6
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0  

dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true              
  assets:     
         - assets/google.png  
